### ISSUE TITLE
Give Martin access to github so that he can assign issues

### ISSUE THREAD

**Issue by MartinZugs** [SoftwareSystemsLaboratory/Metrics-Dashboard#47]
Currently @MartinZugs does not have access to the github repo so that I can manage the kanban board or any of the issues. It would be helpful if I could be given permissions to do that so that he could help maintain the issues and the sprint planning.

Acceptance Criteria:
1) @NicholasSynovic gives @MartinZugs access and confirm that he can assign issues and move them to done

(Thank you!)

**Comment by NicholasSynovic** [comment]
I invited @MartinZugs to the Metrics-Dashboard team and gave him Write permissions.
